// rathena msg_athena.conf
// Configuração da mensagem do Login-Server
// -----------------------
0: ID não registrado.
1: Senha incorreta.
2: Conta expirada.
3: Rejeitado do servidor.
4: Bloqueado por GM.
5: Não é mais recente exe de jogo.
6: Banido.
7: Over-pupulação do servidor.
8: Limite da conta da empresa
9: Proibição por dba
10: Email não confirmado
11: Proibição por GM
12: Trabalhando em DB
13: Auto-trava
14: Grupo não permitido
15: Grupo não permitido
16: Conta perdida.
17: As informações de login permanecem.
18: Investigação de hackers.
19: Investigação de bugs.
20: Excluindo char.
21: Excluindo o Char.
22: Erro desconhecido.
